# This is a config for E2B sandbox template.
# You can use template ID (0ddiun3ymttcn7vpq2rg) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("0ddiun3ymttcn7vpq2rg") # Sync sandbox
# sandbox = await AsyncSandbox.create("0ddiun3ymttcn7vpq2rg") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('0ddiun3ymttcn7vpq2rg')

team_id = "8d9309db-68f7-435b-90fa-6ae394825d74"
memory_mb = 2_048
cpu_count = 2
start_cmd = "/app/start.sh"
dockerfile = "Dockerfile"
template_id = "0ddiun3ymttcn7vpq2rg"
