'use client';

import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useResearchStore } from '@/lib/store';
import { authHeaders } from '@/lib/auth';
import ReactMarkdown from 'react-markdown';
import { Copy, Download, Loader2, ListTree, ExternalLink, Globe, RefreshCcw, Check, FileText, File as FileIcon, Sparkles } from 'lucide-react';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx';
import { saveAs } from 'file-saver';

import remarkGfm from 'remark-gfm';

export function SessionContent({ onRegenerate }: { onRegenerate?: () => void }) {
  const [activeTab, setActiveTab] = useState('report');
  const [isCopying, setIsCopying] = useState(false);
  const [showExportMenu, setShowExportMenu] = useState(false);
  const [summary, setSummary] = useState('');
  const [isSummarizing, setIsSummarizing] = useState(false);
  const [summaryError, setSummaryError] = useState('');
  const summarizedReportRef = useRef<string | null>(null);
  const report = useResearchStore((s) => s.report);
  const query = useResearchStore((s) => s.query);
  const searchResults = useResearchStore((s) => s.searchResults);
  const scrapedResults = useResearchStore((s) => s.scrapedResults);
  const isProcessing = useResearchStore((s) => s.isProcessing);

  const handleCopy = async () => {
    if (!report) return;
    try {
      await navigator.clipboard.writeText(report);
      setIsCopying(true);
      toast.success('Report copied to clipboard');
      setTimeout(() => setIsCopying(false), 2000);
    } catch (err) {
      toast.error('Failed to copy report');
    }
  };

  const generateSummary = useCallback(async () => {
    if (!report) return;
    setIsSummarizing(true);
    setSummaryError('');
    try {
      const res = await fetch('/api/agent/research/summarize', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...authHeaders() },
        body: JSON.stringify({ report }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error || 'Failed to generate summary');
      setSummary(data.summary || '');
    } catch (err) {
      setSummaryError(err instanceof Error ? err.message : 'Failed to generate summary');
    } finally {
      // Mark this report as attempted so we don't auto-retry in a loop;
      // the user can still regenerate manually.
      summarizedReportRef.current = report;
      setIsSummarizing(false);
    }
  }, [report]);

  // Lazily generate the summary the first time the Summary tab is opened for a
  // given report (and re-generate if the report itself changes).
  useEffect(() => {
    if (
      activeTab === 'summary' &&
      report &&
      !isSummarizing &&
      summarizedReportRef.current !== report
    ) {
      generateSummary();
    }
  }, [activeTab, report, isSummarizing, generateSummary]);

  const exportToPDF = () => {
    if (!report) return;
    try {
      const doc = new jsPDF();
      const filename = `${query?.slice(0, 30) || 'research-report'}.pdf`;
      const margin = 20;
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const contentWidth = pageWidth - (2 * margin);
      let y = margin;

      // Helper for footer
      const addFooter = (pdfDoc: any) => {
        const totalPages = pdfDoc.internal.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
          pdfDoc.setPage(i);
          pdfDoc.setFont('helvetica', 'italic');
          pdfDoc.setFontSize(8);
          pdfDoc.setTextColor(150, 150, 150);
          pdfDoc.text(
            'This report is generated by KnowYourLead by DragNFly AI powered Workbench',
            pageWidth / 2,
            pageHeight - 10,
            { align: 'center' }
          );
        }
      };

      // Helper to check and add page
      const checkPageBreak = (neededHeight: number) => {
        if (y + neededHeight > pageHeight - margin - 15) { // Leave room for footer
          doc.addPage();
          y = margin;
          return true;
        }
        return false;
      };

      // Header: Start with "Research Report" instead of query
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(22);
      doc.setTextColor(15, 59, 122); // #0F3B7A
      checkPageBreak(15);
      doc.text('Research Report', margin, y);
      y += 15;

      // Body Content
      const lines = report.split('\n');
      let inTable = false;
      let tableRows: string[][] = [];

      for (let i = 0; i < lines.length; i++) {
        let line = lines[i];

        // --- Table Detection ---
        if (line.trim().startsWith('|')) {
          if (!inTable) {
            inTable = true;
            tableRows = [];
          }
          // Skip the separator line |---|---|
          if (line.includes('---')) continue;
          
          const row = line.split('|').filter(cell => cell.trim() !== '').map(cell => cell.trim());
          if (row.length > 0) tableRows.push(row);
          
          // If next line is not a table line, render the table
          const nextLine = lines[i + 1];
          if (!nextLine || !nextLine.trim().startsWith('|')) {
            inTable = false;
            if (tableRows.length > 0) {
              const head = [tableRows[0]];
              const body = tableRows.slice(1);
              
              autoTable(doc, {
                head: head,
                body: body,
                startY: y,
                margin: { left: margin, right: margin },
                theme: 'striped',
                headStyles: { fillColor: [15, 59, 122], textColor: 255 },
                styles: { fontSize: 9, cellPadding: 3 },
                didDrawPage: (data: any) => {
                  y = data.cursor.y;
                }
              });
              y = (doc as any).lastAutoTable.finalY + 10;
            }
          }
          continue;
        }

        if (!line.trim()) {
          y += 5;
          continue;
        }

        let fontSize = 11;
        let fontStyle = 'normal';
        let color = [51, 65, 85]; // Default slate

        // Simple Markdown Parsing for PDF
        if (line.startsWith('# ')) {
          fontSize = 16;
          fontStyle = 'bold';
          line = line.replace('# ', '');
          color = [15, 59, 122];
          y += 5;
        } else if (line.startsWith('## ')) {
          fontSize = 14;
          fontStyle = 'bold';
          line = line.replace('## ', '');
          color = [15, 59, 122];
          y += 4;
        } else if (line.startsWith('### ')) {
          fontSize = 12;
          fontStyle = 'bold';
          line = line.replace('### ', '');
          y += 3;
        }

        // Handle Links [text](url) -> text (url)
        line = line.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '$1 ($2)');

        doc.setFont('helvetica', fontStyle);
        doc.setFontSize(fontSize);
        doc.setTextColor(color[0], color[1], color[2]);

        const splitLines = doc.splitTextToSize(line, contentWidth);
        const lineHeight = fontSize * 0.5;

        for (const sLine of splitLines) {
          if (checkPageBreak(lineHeight)) {
            doc.setFont('helvetica', fontStyle);
            doc.setFontSize(fontSize);
            doc.setTextColor(color[0], color[1], color[2]);
          }
          doc.text(sLine, margin, y);
          y += lineHeight;
        }
        y += 2;
      }

      addFooter(doc);
      doc.save(filename);
      toast.success('PDF downloaded');
    } catch (err) {
      console.error(err);
      toast.error('Failed to export PDF');
    }
  };

  const exportToDOCX = async () => {
    if (!report) return;
    try {
      const sections = report.split('\n').map(line => {
        let level: any = HeadingLevel.HEADING_1;
        let text = line;
        
        if (line.startsWith('### ')) {
          level = HeadingLevel.HEADING_3;
          text = line.replace('### ', '');
        } else if (line.startsWith('## ')) {
          level = HeadingLevel.HEADING_2;
          text = line.replace('## ', '');
        } else if (line.startsWith('# ')) {
          level = HeadingLevel.HEADING_1;
          text = line.replace('# ', '');
        } else {
          return new Paragraph({
            children: [new TextRun(line)],
            spacing: { after: 200 }
          });
        }
        
        return new Paragraph({
          text,
          heading: level,
          spacing: { before: 400, after: 200 }
        });
      });

      const doc = new Document({
        sections: [{
          properties: {},
          children: sections
        }]
      });

      const blob = await Packer.toBlob(doc);
      saveAs(blob, `${query?.slice(0, 30) || 'research-report'}.docx`);
      toast.success('DOCX downloaded');
    } catch (err) {
      console.error(err);
      toast.error('Failed to export DOCX');
    }
  };

  // Extract headings for TOC
  const headings = React.useMemo(() => {
    if (!report) return [];
    const regex = /^(#{1,3})\s+(.+)$/gm;
    const extracted: { id: string; text: string; level: number }[] = [];
    let match;
    while ((match = regex.exec(report)) !== null) {
      extracted.push({
        level: match[1].length,
        text: match[2].trim(),
        id: match[2].trim().toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]/g, '')
      });
    }
    return extracted;
  }, [report]);

  const tabs = [
    { id: 'report', label: 'Report' },
    { id: 'summary', label: 'Summary' },
    { id: 'sources', label: `Sources (${searchResults.length})` },
    { id: 'scraped', label: `Scraped (${scrapedResults.length})` },
    { id: 'citations', label: 'Citations' },
    { id: 'notes', label: 'Notes' },
  ];

  return (
    <div className="flex gap-6 mt-8">
      {/* Main Content Area */}
      <div className="flex-1 bg-white rounded-xl border shadow-sm flex flex-col overflow-hidden min-h-[600px]">
        {/* Tabs */}
        <div className="flex items-center justify-between border-b border-slate-200 px-2">
          <div className="flex">
            {tabs.map(tab => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={cn(
                  "px-4 py-3 text-sm font-bold border-b-2 transition-colors",
                  activeTab === tab.id 
                    ? "border-blue-600 text-blue-600" 
                    : "border-transparent text-slate-500 hover:text-slate-900 hover:border-slate-300"
                )}
              >
                {tab.label}
              </button>
            ))}
          </div>
          <div className="flex items-center gap-2 px-2">
            {onRegenerate && (
              <button 
                onClick={onRegenerate}
                disabled={isProcessing}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-blue-600 hover:text-blue-700 hover:bg-blue-50 rounded-md transition-colors disabled:opacity-50"
              >
                <RefreshCcw className={cn("h-3.5 w-3.5", isProcessing && "animate-spin")} />
                Regenerate
              </button>
            )}
            <button 
              onClick={handleCopy}
              disabled={!report}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-slate-500 hover:text-slate-900 hover:bg-slate-50 rounded-md transition-colors disabled:opacity-50"
            >
              {isCopying ? <Check className="h-3.5 w-3.5 text-green-500" /> : <Copy className="h-3.5 w-3.5" />}
              {isCopying ? 'Copied' : 'Copy'}
            </button>
            
            <div className="relative">
              <button 
                onClick={() => setShowExportMenu(!showExportMenu)}
                disabled={!report}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-slate-500 hover:text-slate-900 hover:bg-slate-50 rounded-md transition-colors disabled:opacity-50"
              >
                <Download className="h-3.5 w-3.5" />
                Export
              </button>
              
              {showExportMenu && (
                <div className="absolute right-0 mt-1 w-48 bg-white border border-slate-200 rounded-lg shadow-lg z-50 py-1 overflow-hidden">
                  <button 
                    onClick={() => {
                      exportToDOCX();
                      setShowExportMenu(false);
                    }}
                    className="w-full flex items-center gap-2 px-4 py-2 text-sm text-slate-700 hover:bg-slate-50 transition-colors text-left"
                  >
                    <FileText className="h-4 w-4 text-blue-600" />
                    Download as DOCX
                  </button>
                  <button 
                    onClick={() => {
                      exportToPDF();
                      setShowExportMenu(false);
                    }}
                    className="w-full flex items-center gap-2 px-4 py-2 text-sm text-slate-700 hover:bg-slate-50 transition-colors text-left"
                  >
                    <FileIcon className="h-4 w-4 text-red-600" />
                    Download as PDF
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Tab Content */}
        <div className="flex-1 p-6 lg:p-8 overflow-y-auto">
          {activeTab === 'report' && (
            <div className="prose prose-slate max-w-none">
              {!report && isProcessing && (
                <div className="flex flex-col items-center justify-center h-64 text-slate-400 space-y-4">
                  <Loader2 className="h-8 w-8 animate-spin text-blue-500" />
                  <p>Agent is compiling the report...</p>
                </div>
              )}
              {!report && !isProcessing && (
                <p className="text-slate-400 italic">No report generated yet.</p>
              )}
              {report && (
                <ReactMarkdown
                  remarkPlugins={[remarkGfm]}
                  components={{
                    h1: ({node, ...props}) => {
                      const id = props.children?.toString().toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]/g, '');
                      return <h1 id={id} className="text-3xl font-bold mb-6 text-[#0F3B7A]" {...props} />
                    },
                    h2: ({node, ...props}) => {
                      const id = props.children?.toString().toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]/g, '');
                      return <h2 id={id} className="text-[10px] font-bold mt-8 mb-4 border-b border-slate-200 pb-2 text-[#0F3B7A] uppercase tracking-widest" {...props} />
                    },
                    h3: ({node, ...props}) => {
                      const id = props.children?.toString().toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]/g, '');
                      return <h3 id={id} className="text-lg font-bold mt-6 mb-3 text-slate-900" {...props} />
                    },
                    p: ({node, ...props}) => (
                      <p className="text-slate-600 leading-relaxed mb-4" {...props} />
                    ),
                    li: ({node, ...props}) => (
                      <li className="text-slate-600 leading-relaxed" {...props} />
                    ),
                    a: ({node, ...props}) => (
                      <a className="text-blue-600 hover:underline font-medium" target="_blank" rel="noopener noreferrer" {...props} />
                    ),
                    table: ({node, ...props}) => (
                      <div className="overflow-x-auto mb-6">
                        <table className="w-full text-sm text-left text-slate-600 border border-slate-200 rounded-lg" {...props} />
                      </div>
                    ),
                    thead: ({node, ...props}) => (
                      <thead className="text-xs text-slate-700 uppercase bg-slate-50 border-b border-slate-200" {...props} />
                    ),
                    th: ({node, ...props}) => (
                      <th className="px-6 py-3 font-bold" {...props} />
                    ),
                    td: ({node, ...props}) => (
                      <td className="px-6 py-4 border-b border-slate-100" {...props} />
                    ),
                    img: ({node, ...props}) => (
                      // eslint-disable-next-line @next/next/no-img-element
                      <img className="rounded-lg shadow-sm border border-slate-200 my-6 max-w-full h-auto" loading="lazy" {...props} alt={props.alt || "Research Image"} />
                    ),
                  }}
                >
                  {report}
                </ReactMarkdown>
              )}
            </div>
          )}

          {activeTab === 'summary' && (
            <div>
              {!report ? (
                <p className="text-slate-400 italic">No report generated yet — the summary will appear here once a report is ready.</p>
              ) : (
                <>
                  <div className="flex items-center justify-between mb-6">
                    <div className="flex items-center gap-2 text-sm font-bold text-[#0F3B7A]">
                      <Sparkles className="h-4 w-4" />
                      Executive Summary
                    </div>
                    <button
                      onClick={generateSummary}
                      disabled={isSummarizing}
                      className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-blue-600 hover:text-blue-700 hover:bg-blue-50 rounded-md transition-colors disabled:opacity-50"
                    >
                      <RefreshCcw className={cn("h-3.5 w-3.5", isSummarizing && "animate-spin")} />
                      Regenerate
                    </button>
                  </div>

                  {isSummarizing && (
                    <div className="flex flex-col items-center justify-center h-64 text-slate-400 space-y-4">
                      <Loader2 className="h-8 w-8 animate-spin text-blue-500" />
                      <p>Summarizing the report...</p>
                    </div>
                  )}

                  {!isSummarizing && summaryError && (
                    <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">
                      {summaryError}
                      <button onClick={generateSummary} className="ml-2 font-bold underline">Try again</button>
                    </div>
                  )}

                  {!isSummarizing && !summaryError && summary && (
                    <div className="prose prose-slate max-w-none">
                      <ReactMarkdown
                        remarkPlugins={[remarkGfm]}
                        components={{
                          h2: ({node, ...props}) => (
                            <h2 className="text-sm font-bold mt-6 mb-3 text-[#0F3B7A] uppercase tracking-widest" {...props} />
                          ),
                          p: ({node, ...props}) => (
                            <p className="text-slate-600 leading-relaxed mb-4" {...props} />
                          ),
                          li: ({node, ...props}) => (
                            <li className="text-slate-600 leading-relaxed" {...props} />
                          ),
                          a: ({node, ...props}) => (
                            <a className="text-blue-600 hover:underline font-medium" target="_blank" rel="noopener noreferrer" {...props} />
                          ),
                        }}
                      >
                        {summary}
                      </ReactMarkdown>
                    </div>
                  )}
                </>
              )}
            </div>
          )}

          {activeTab === 'sources' && (
            <div className="space-y-4">
              {searchResults.length === 0 && <p className="text-slate-400">No sources scanned yet.</p>}
              {searchResults.map((result, i) => (
                <div key={i} className="p-4 rounded-xl border border-slate-200 bg-slate-50">
                  <a href={result.url} target="_blank" rel="noreferrer" className="font-bold text-blue-600 hover:underline flex items-center gap-1 mb-1">
                    {result.title}
                    <ExternalLink className="h-3 w-3" />
                  </a>
                  <p className="text-xs text-slate-400 mb-2">{result.url}</p>
                  <p className="text-sm text-slate-600">{result.snippet}</p>
                </div>
              ))}
            </div>
          )}

          {activeTab === 'scraped' && (
            <div className="space-y-4">
              {scrapedResults.length === 0 && <p className="text-slate-400">No pages scraped yet.</p>}
              {scrapedResults.map((result, i) => (
                <div key={i} className="p-4 rounded-xl border border-slate-200 bg-slate-50">
                  <h4 className="font-bold text-slate-900 mb-2">{result.title}</h4>
                  <div className="bg-white rounded p-3 text-xs font-mono text-slate-600 overflow-y-auto max-h-32 border border-slate-200">
                    {result.content.slice(0, 500)}...
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Right Sidebar - Table of Contents */}
      <div className="hidden xl:block w-72 shrink-0">
        <div className="sticky top-24 bg-white rounded-xl border border-slate-200 shadow-sm p-5">
          <div className="flex items-center gap-2 text-[10px] font-bold tracking-widest text-slate-400 uppercase mb-4">
            <ListTree className="h-4 w-4" />
            Contents
          </div>
          <div className="space-y-1">
            {headings.length === 0 ? (
              <p className="text-sm text-slate-400 italic">Waiting for report...</p>
            ) : (
              headings.map((h, i) => (
                <a
                  key={i}
                  href={`#${h.id}`}
                  className={cn(
                    "block py-1.5 text-sm transition-colors hover:text-blue-600",
                    h.level === 1 ? "font-bold text-blue-600" :
                    h.level === 2 ? "pl-3 text-slate-900 font-semibold" :
                    "pl-6 text-slate-500 text-xs"
                  )}
                  onClick={(e) => {
                    e.preventDefault();
                    document.getElementById(h.id)?.scrollIntoView({ behavior: 'smooth' });
                  }}
                >
                  {h.text}
                </a>
              ))
            )}
          </div>

          {/* Sources Summary Widget */}
          <div className="mt-8 pt-6 border-t border-slate-200">
            <div className="flex items-center justify-between text-[10px] font-bold tracking-widest text-slate-400 uppercase mb-4">
              <span className="flex items-center gap-2">
                <Globe className="h-4 w-4" />
                Sources
              </span>
              <span className="text-blue-600">{searchResults.length}</span>
            </div>
            <div className="space-y-2">
              {searchResults.slice(0, 4).map((s, i) => (
                <a key={i} href={s.url} target="_blank" rel="noreferrer" className="flex items-center gap-3 p-2 rounded-lg hover:bg-slate-50 transition-colors">
                  <div className="h-6 w-6 rounded bg-blue-50 text-blue-600 flex items-center justify-center shrink-0">
                    <span className="text-[10px] font-bold">{s.hostName?.charAt(0).toUpperCase() || 'W'}</span>
                  </div>
                  <div className="overflow-hidden">
                    <p className="text-xs font-bold truncate text-slate-900">{s.title}</p>
                    <p className="text-[10px] text-slate-500 truncate">{s.hostName}</p>
                  </div>
                </a>
              ))}
              {searchResults.length > 4 && (
                <button 
                  className="w-full py-2 mt-2 text-xs font-bold text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
                  onClick={() => setActiveTab('sources')}
                >
                  View all {searchResults.length} sources
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
